version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kaplabs-jobs
    container_name: kaplabs-jobs-app
    ports:
      - "5173:5173"
    environment:
      - SECRET_KEY
      - ALGORITHM
      - ACCESS_TOKEN_EXPIRE_MINUTES
      - MONGODB_URL
      - SERVER_HOST
      - SERVER_PORT
      - FRONTEND_URL
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
