name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name 'Fork Sync Bot'
          git config user.email 'fork-sync-bot@github.com'

      - name: Add upstream repository
        run: git remote add upstream https://github.com/SimplifyJobs/Summer2025-Internships.git

      - name: Fetch upstream
        run: |
          git fetch upstream
          git checkout dev

      - name: Sync conflicting files
        run: |
          # Try merge to identify conflicts
          if ! git merge-tree $(git merge-base HEAD upstream/dev) HEAD upstream/dev | grep -q "^<<<<<<< .mine"; then
            echo "No conflicts found, keeping our files"
            exit 0
          fi
          
          # Get list of conflicting files
          CONFLICT_FILES=$(git merge-tree $(git merge-base HEAD upstream/dev) HEAD upstream/dev | grep "^<<<<<<< .mine" -B 1 | grep "^+" | cut -d' ' -f2)
          
          # Checkout only conflicting files from upstream
          for file in $CONFLICT_FILES; do
            git checkout upstream/dev -- "$file"
            git add "$file"
          done
          
          # Commit and push changes
          git commit -m "sync: Update conflicting files from upstream"
          git push origin dev
