name: sync-fork
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4  # Add this step to checkout the repository
      
      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      
      - name: Sync Fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add upstream https://github.com/SimplifyJobs/Summer2025-Internships.git
          git fetch upstream
          git checkout ${{ github.ref_name }}
          git merge upstream/main --no-edit
          git push origin ${{ github.ref_name }}