name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: dev
          persist-credentials: false

      # Set up git configuration
      - name: Set up Git config
        run: |
          git config user.name 'Fork Sync Bot'
          git config user.email 'fork-sync-bot@github.com'

      # Add upstream remote
      - name: Add upstream repository
        run: git remote add upstream https://github.com/SimplifyJobs/Summer2025-Internships.git

      # Fetch upstream changes
      - name: Fetch upstream
        run: git fetch upstream

      # Merge upstream/main into dev
      - name: Merge upstream changes
        run: git merge upstream/dev --allow-unrelated-histories --no-edit

      # Push changes back to dev branch
      - name: Push changes
        run: |
          git push origin dev
